### ISSUE TITLE
Vendoring dependencies for more reliable upgrades

### ISSUE THREAD

**Issue by conradkdotcom** [conradkdotcom/rooster#36]
In order to make dependency upgrade easier to audit, Rooster needs vendored dependencies.

This is probably the right tool for the job: https://github.com/alexcrichton/cargo-vendor

Are you up for the task?

**Comment by yamnikov-oleg** [comment]
I will take this task now, before `rooster weak` is implemented, so that `zxcvbn` would be vendored right away.

**Comment by conradkdotcom** [comment]
Awesome, thanks a lot @yamnikov-oleg ! 👍 😃

**Comment by yamnikov-oleg** [comment]
There is a problem with `xcb` crate which is used by `x11-clipboard`. The crate generates sources on every build and these sources always come out different because: (1) there is a timestamp commented in them; (2) some elements in the generated code are being randomly reordered.

On the other hand, cargo keeps checksums of all the vendored crates and their files. `xcb` fails checksum test on the second build after `cargo-vendor` execution.

There is a possibility to use cargo's `[replace]` and `[patch]` sections to bypass the checksum test. But even this way working tree is left dirty on every rebuild.

I'm thinking about making a PR to `xcb` repository to make source generation determinate for single crate version. If you have better ideas, I'd like to hear them :)

**Comment by conradkdotcom** [comment]
Good spot, @yamnikov-oleg ! Would be awesome if the `xcb` crate could "just work" with cargo-vendor. I'm sure if you make a PR it would be a big win for the Rust ecosystem 👍 then again I don't know how much work it is. If changing `xcb` is not possible, the `[replace]` and `[patch]` method would be OK too.
